[package]
name = "cargo-next"
description = "A cargo subcommand to set the next crate version"
version = "0.1.1"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/conventional-commits-rs/cargo-next"
authors = ["Sven Lechner <SirWindfield@users.noreply.github.com>"]
edition = "2018"

[dependencies]
toml_edit = "0.2.0"
pico-args = "0.3.3"
